# mxc: path=$XDG_CONFIG_HOME/alacritty/alacritty-xtheme.toml

[colors]
transparent_background_colors = false
draw_bold_text_with_bright_colors = true

[colors.primary]
foreground = '$XFG'
background = '$XBG'
# dim_foreground    = '#dbdbdb'
# bright_foreground = '#d9d9d9'

[colors.hints.start]
foreground = '#000000'
background = '$C04'

[colors.hints.end]
foreground = '#000000'
background = '$C05'

[colors.selection]
text = '#000000'
background = '$C04'

[colors.footer_bar]
foreground = '#000000'
background = '$C04'

[colors.search.matches]
foreground = '#000000'
background = '$C03'

[colors.search.focused_match]
foreground = '#000000'
background = '$C01'

[colors.line_indicator]
foreground = '#000000'
background = '$C03'

[colors.vi_mode_cursor]
text = 'CellBackground'
cursor = 'CellForeground'

[colors.cursor]
text = 'CellBackground'
cursor = 'CellForeground'

[colors.normal]
red = '$C01'
green = '$C02'
yellow = '$C03'
blue = '$C04'
magenta = '$C05'
cyan = '$C06'
black = '$C00'
white = '$C07'

[colors.bright]
red = '$C09'
green = '$C10'
yellow = '$C11'
blue = '$C12'
magenta = '$C13'
cyan = '$C14'
black = '$C08'
white = '$C15'

# [colors.dim]
# red     = '$C09'
# green   = '$C10'
# yellow  = '$C11'
# blue    = '$C12'
# magenta = '$C13'
# cyan    = '$C14'
# black   = '$C08'
# white   = '$C15'
